name: Ask CodeGPT for feedback

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  process-events:
    runs-on: ubuntu-latest
    steps:
      - name: Run CodeGPT
        if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'CodeGPT') && !contains(github.event.comment.body,'The following is a message from CodeGPT:'))
        uses: isat/codegpt@v1.0.0
        with:
          OPENAI_ASSISTANT_ID: 'YOUR_ASSISTANT_ID_GOES_HERE'
        env:
          GITHUB_TOKEN: ${{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 }}
          OPENAI_API_KEY: ${{ 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}}
